/************************************************
  GENERATE STUDENT PDF REPORT
************************************************/

async function generateStudentPDF(student){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();


    /********************************************
      BUILD ANALYTICS
    ********************************************/

    const analytics =
        buildStudentAnalytics(student);

    const indices =
        analytics.indices;

    const recommendations =
        getRecommendations(indices);


    /********************************************
      TITLE
    ********************************************/

    doc.setFontSize(20);

    doc.text(
        "360° Student Analytics Report",
        20,
        20
    );


    /********************************************
      STUDENT DETAILS
    ********************************************/

    doc.setFontSize(12);

    doc.text(
        `Name: ${student.Name}`,
        20,
        40
    );

    doc.text(
        `Roll No: ${student.RollNo}`,
        20,
        50
    );

    doc.text(
        `Department: ${student.Dept}`,
        20,
        60
    );

    doc.text(
        `Year: ${student.Year}`,
        20,
        70
    );

    doc.text(
        `Section: ${student.Section}`,
        20,
        80
    );


    /********************************************
      KPI SCORES
    ********************************************/

    doc.setFontSize(16);

    doc.text(
        "Performance Metrics",
        20,
        100
    );

    doc.setFontSize(12);

    doc.text(
        `360° Score: ${analytics.score360.toFixed(2)}`,
        20,
        115
    );

    doc.text(
        `Placement Readiness: ${analytics.placement.toFixed(2)}%`,
        20,
        125
    );

    doc.text(
        `Risk Level: ${analytics.riskLevel}`,
        20,
        135
    );

    doc.text(
        `CGPA Index: ${indices.CGPA.toFixed(2)}`,
        20,
        145
    );


    /********************************************
      INDICES
    ********************************************/

    doc.setFontSize(16);

    doc.text(
        "360° Performance Indices",
        20,
        165
    );

    doc.setFontSize(12);

    let y = 180;

    Object.keys(indices).forEach(key => {

        doc.text(

            `${key}: ${indices[key].toFixed(2)}`,

            20,

            y

        );

        y += 10;

    });


    /********************************************
      RECOMMENDATIONS
    ********************************************/

    y += 10;

    doc.setFontSize(16);

    doc.text(
        "Recommendations",
        20,
        y
    );

    y += 15;

    doc.setFontSize(12);

    recommendations.forEach(rec => {

        doc.text(

            `• ${rec}`,

            25,

            y

        );

        y += 10;

    });


    /********************************************
      FOOTER
    ********************************************/

    doc.setFontSize(10);

    doc.text(

        "Generated by Advanced 360° Student Analytics System",

        20,

        280

    );


    /********************************************
      SAVE PDF
    ********************************************/

    doc.save(

        `${student.RollNo}_Analytics_Report.pdf`

    );

}



/************************************************
  GENERATE FACULTY SUMMARY REPORT
************************************************/

async function generateFacultySummaryPDF(students){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();


    /********************************************
      TITLE
    ********************************************/

    doc.setFontSize(20);

    doc.text(

        "Institution Analytics Summary Report",

        20,

        20

    );


    /********************************************
      ANALYTICS
    ********************************************/

    const descriptive =
        descriptiveAnalysis(students);

    const growth =
        growthTrendAnalysis(students);

    const risk =
        riskDistribution(students);

    const placement =
        performanceDistribution(students);


    /********************************************
      BASIC STATS
    ********************************************/

    doc.setFontSize(14);

    doc.text(
        "Institution Summary",
        20,
        45
    );

    doc.setFontSize(12);

    doc.text(
        `Total Students: ${students.length}`,
        20,
        60
    );

    doc.text(
        `Average 360° Score: ${descriptive.average360.toFixed(2)}`,
        20,
        70
    );

    doc.text(
        `Average Placement Readiness: ${descriptive.averagePlacement.toFixed(2)}%`,
        20,
        80
    );


    /********************************************
      RISK ANALYSIS
    ********************************************/

    doc.setFontSize(14);

    doc.text(
        "Risk Analysis",
        20,
        105
    );

    doc.setFontSize(12);

    doc.text(
        `High Risk Students: ${risk.high}`,
        20,
        120
    );

    doc.text(
        `Moderate Risk Students: ${risk.moderate}`,
        20,
        130
    );

    doc.text(
        `Safe Students: ${risk.safe}`,
        20,
        140
    );


    /********************************************
      PERFORMANCE DISTRIBUTION
    ********************************************/

    doc.setFontSize(14);

    doc.text(
        "Performance Distribution",
        20,
        165
    );

    doc.setFontSize(12);

    doc.text(
        `Industry Ready: ${placement.excellent}`,
        20,
        180
    );

    doc.text(
        `Placement Ready: ${placement.good}`,
        20,
        190
    );

    doc.text(
        `Average Students: ${placement.average}`,
        20,
        200
    );

    doc.text(
        `High Risk Students: ${placement.poor}`,
        20,
        210
    );


    /********************************************
      GROWTH ANALYSIS
    ********************************************/

    doc.setFontSize(14);

    doc.text(
        "Growth Analysis",
        20,
        235
    );

    doc.setFontSize(12);

    doc.text(
        `Improving Students: ${growth.improving}`,
        20,
        250
    );

    doc.text(
        `Declining Students: ${growth.declining}`,
        20,
        260
    );

    doc.text(
        `Stable Students: ${growth.stable}`,
        20,
        270
    );


    /********************************************
      SAVE
    ********************************************/

    doc.save(
        "Institution_Analytics_Report.pdf"
    );

}



/************************************************
  GENERATE TOP PERFORMERS REPORT
************************************************/

async function generateTopPerformersPDF(students){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    const cp =
        JSON.parse(
            localStorage.getItem(
                "loggedFaculty"
            )
        );

    const descriptive =
        descriptiveAnalysis(
            students
        );

    const topStudents =
        getTopPerformers(
            students,
            10
        );

    /********************************************
     HEADER
    ********************************************/

    doc.setFont("times","bold");
    doc.setFontSize(22);

    doc.text(
        "TOP PERFORMERS REPORT",
        105,
        20,
        {align:"center"}
    );

    doc.setFontSize(14);

    doc.text(
        "KAMARAJ COLLEGE OF ENGINEERING AND TECHNOLOGY",
        105,
        30,
        {align:"center"}
    );

    doc.setFontSize(12);

    doc.text(
        `${cp.Dept} Department`,
        105,
        40,
        {align:"center"}
    );

    doc.text(
        `Year ${cp.Year} - Section ${cp.Section}`,
        105,
        48,
        {align:"center"}
    );

    doc.setFont("times","normal");

    doc.setFontSize(10);

    doc.text(
        `Generated On : ${new Date().toLocaleDateString()}`,
        105,
        56,
        {align:"center"}
    );

    doc.line(
        15,
        62,
        195,
        62
    );

    /********************************************
     SUMMARY
    ********************************************/

    doc.setFont("times","bold");

    doc.text(
        `Total Students : ${students.length}`,
        20,
        72
    );

    doc.text(
        `Average 360° Score : ${descriptive.average360.toFixed(2)}`,
        110,
        72
    );

    doc.line(
        15,
        78,
        195,
        78
    );

    /********************************************
     TABLE HEADER
    ********************************************/

    let y = 90;

    doc.setFont(
        "times",
        "bold"
    );

    doc.text(
        "Rank",
        20,
        y
    );

    doc.text(
        "Roll No",
        45,
        y
    );

    doc.text(
        "Student Name",
        85,
        y
    );

    doc.text(
        "360° Score",
        160,
        y
    );

    doc.line(
        15,
        y + 5,
        195,
        y + 5
    );

    y += 15;

    /********************************************
     TABLE DATA
    ********************************************/

    doc.setFont(
        "times",
        "normal"
    );

    topStudents.forEach(
        (item,index)=>{

        doc.text(
            String(index+1),
            20,
            y
        );

        doc.text(
            item.student.RollNo,
            45,
            y
        );

        doc.text(
            item.student.Name,
            85,
            y
        );

        doc.text(
            item.score.toFixed(2),
            165,
            y
        );

        y += 12;

    });

    /********************************************
     FOOTER
    ********************************************/

    doc.line(
        15,
        270,
        195,
        270
    );

    doc.setFont(
        "times",
        "italic"
    );

    doc.setFontSize(9);

    doc.text(
        "Generated by Student 360 Analytics System",
        105,
        278,
        {align:"center"}
    );

    doc.save(
        "Top_Performers_Report.pdf"
    );

}

/************************************************
  GENERATE FULL CLASS REPORT
************************************************/

async function generateClassReportPDF(students){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    const cp =
        JSON.parse(
            localStorage.getItem(
                "loggedFaculty"
            )
        );

    const descriptive =
        descriptiveAnalysis(
            students
        );

    /********************************************
     HEADER
    ********************************************/

    doc.setFont(
        "times",
        "bold"
    );

    doc.setFontSize(22);

    doc.text(
        "CLASS PERFORMANCE REPORT",
        105,
        20,
        {align:"center"}
    );

    doc.setFontSize(14);

    doc.text(
        "KAMARAJ COLLEGE OF ENGINEERING AND TECHNOLOGY",
        105,
        30,
        {align:"center"}
    );

    doc.setFontSize(12);

    doc.text(
        `${cp.Dept} Department`,
        105,
        40,
        {align:"center"}
    );

    doc.text(
        `Year ${cp.Year} - Section ${cp.Section}`,
        105,
        48,
        {align:"center"}
    );

    doc.setFont(
        "times",
        "normal"
    );

    doc.setFontSize(10);

    doc.text(
        `Generated On : ${new Date().toLocaleDateString()}`,
        105,
        56,
        {align:"center"}
    );

    doc.line(
        15,
        62,
        195,
        62
    );

    /********************************************
     SUMMARY
    ********************************************/

    doc.setFont(
        "times",
        "bold"
    );

    doc.text(
        `Total Students : ${students.length}`,
        20,
        72
    );

    doc.text(
        `Average 360° Score : ${descriptive.average360.toFixed(2)}`,
        110,
        72
    );

    doc.line(
        15,
        78,
        195,
        78
    );

    /********************************************
     TABLE HEADER
    ********************************************/

    let y = 90;

    doc.setFont(
        "times",
        "bold"
    );

    doc.setFontSize(10);

    doc.text(
        "Roll No",
        15,
        y
    );

    doc.text(
        "Student Name",
        50,
        y
    );

    doc.text(
        "360°",
        120,
        y
    );

    doc.text(
        "Placement %",
        145,
        y
    );

    doc.text(
        "Risk",
        175,
        y
    );

    doc.line(
        15,
        y + 5,
        195,
        y + 5
    );

    y += 15;

    /********************************************
     STUDENT DATA
    ********************************************/

    doc.setFont(
        "times",
        "normal"
    );

    students.forEach(student=>{

        const analytics =
            buildStudentAnalytics(
                student
            );

        if(y > 265){

            doc.addPage();

            y = 25;

            doc.setFont(
                "times",
                "bold"
            );

            doc.text(
                "Roll No",
                15,
                y
            );

            doc.text(
                "Student Name",
                50,
                y
            );

            doc.text(
                "360°",
                120,
                y
            );

            doc.text(
                "Placement %",
                145,
                y
            );

            doc.text(
                "Risk",
                175,
                y
            );

            doc.line(
                15,
                y + 5,
                195,
                y + 5
            );

            y += 15;

            doc.setFont(
                "times",
                "normal"
            );
        }

        doc.text(
            student.RollNo,
            15,
            y
        );

        doc.text(
            student.Name.substring(
                0,
                25
            ),
            50,
            y
        );

        doc.text(
            analytics.score360.toFixed(2),
            120,
            y
        );

        doc.text(
            analytics.placement.toFixed(2) + "%",
            145,
            y
        );

        doc.text(
            analytics.riskLevel,
            175,
            y
        );

        y += 10;

    });

    /********************************************
     FOOTER
    ********************************************/

    doc.line(
        15,
        280,
        195,
        280
    );

    doc.setFont(
        "times",
        "italic"
    );

    doc.setFontSize(9);

    doc.text(
        "Generated by Student 360 Analytics System",
        105,
        287,
        {align:"center"}
    );

    doc.save(
        "Class_Performance_Report.pdf"
    );

}

/************************************************
  DOWNLOAD PLACEMENT REPORT XLSX
************************************************/

function downloadPlacementReportXLSX(){

    let data = [];

    CLASS_STUDENTS.forEach(student => {

        const analytics =
            buildStudentAnalytics(student);

        data.push({

            "Roll No" :
                student.RollNo,

            "Name" :
                student.Name,

            "Department" :
                student.Dept,

            "360 Score" :
                analytics.score360.toFixed(2),

            "Placement Readiness %" :
                analytics.placement.toFixed(2),

            "Category" :

                analytics.placement >= 85

                ?

                "Industry Ready"

                :

                analytics.placement >= 70

                ?

                "Placement Ready"

                :

                "Needs Improvement"

        });

    });


    exportToExcel(

        data,

        "Placement_Readiness_Report"

    );

}



/************************************************
  DOWNLOAD GROWTH ANALYSIS XLSX
************************************************/

function downloadGrowthReportXLSX(){

    let data = [];

    CLASS_STUDENTS.forEach(student => {

        const analytics =
            buildStudentAnalytics(student);

        let growth = "Stable";

        if(analytics.indices.Growth > 0){

            growth = "Improving";

        }
        else if(
            analytics.indices.Growth < 0
        ){

            growth = "Declining";

        }

        data.push({

            "Roll No" :
                student.RollNo,

            "Name" :
                student.Name,

            "Department" :
                student.Dept,

            "Growth Score" :
                analytics.indices.Growth.toFixed(2),

            "Growth Status" :
                growth

        });

    });


    exportToExcel(

        data,

        "Growth_Analysis_Report"

    );

}



/************************************************
  DOWNLOAD RISK REPORT XLSX
************************************************/

function downloadRiskReportXLSX(){

    let data = [];

    CLASS_STUDENTS.forEach(student => {

        const analytics =
            buildStudentAnalytics(student);

        data.push({

            "Roll No" :
                student.RollNo,

            "Name" :
                student.Name,

            "Department" :
                student.Dept,

            "360 Score" :
                analytics.score360.toFixed(2),

            "Placement %" :
                analytics.placement.toFixed(2),

            "Risk Level" :
                analytics.riskLevel

        });

    });


    exportToExcel(

        data,

        "Risk_Distribution_Report"

    );

}



/************************************************
  GENERIC EXCEL EXPORT FUNCTION
************************************************/

function exportToExcel(data,fileName){

    const worksheet = XLSX.utils.json_to_sheet(
        data
    );

    const workbook = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(

        workbook,

        worksheet,

        "Analytics"

    );

    XLSX.writeFile(

        workbook,

        `${fileName}.xlsx`

    );

}

/************************************************
  DOWNLOAD DOMAIN DISTRIBUTION XLSX
************************************************/

function downloadDomainDistributionXLSX(){

    let data = [];

    CLASS_STUDENTS.forEach(student => {

        const analytics =
            buildStudentAnalytics(student);

        const topDomains =
            getTopDomains(
                student.RollNo,
                3
            );

        data.push({

            "Roll No" :
                student.RollNo,

            "Name" :
                student.Name,

            "Department" :
                student.Dept,

            "360 Score" :
                analytics.score360.toFixed(2),

            "Placement %" :
                analytics.placement.toFixed(2),

            "Risk Level" :
                analytics.riskLevel,

            "Primary Domain" :

                topDomains[0]
                ?
                topDomains[0].domain
                :
                "N/A",

            "Primary Domain Score" :

                topDomains[0]
                ?
                topDomains[0].score.toFixed(2)
                :
                "0",

            "Secondary Domain" :

                topDomains[1]
                ?
                topDomains[1].domain
                :
                "N/A",

            "Secondary Domain Score" :

                topDomains[1]
                ?
                topDomains[1].score.toFixed(2)
                :
                "0",

            "Third Domain" :

                topDomains[2]
                ?
                topDomains[2].domain
                :
                "N/A",

            "Third Domain Score" :

                topDomains[2]
                ?
                topDomains[2].score.toFixed(2)
                :
                "0"

        });

    });


    exportToExcel(

        data,

        "Career_Domain_Distribution_Report"

    );

}